config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cars, only: %w[index show new create] do
    resources :bookings, only: %w[create]
  end
  resources :bookings, only: %w[index]
  patch '/booking/:id/accept', to: 'bookings#acceptBooking', as: :accept_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  
  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, presence: true, numericality: true
  validates :price_per_day, comparison: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def create
        booking = Booking.new(booking_params)
        car = Car.find(params[:car_id])
        booking.car = car
        booking.user = current_user

        if booking.save
            redirect_to car_path(car), notice: "Booking successfully requested !"
        else
            redirect_to car_path(car), alert: "An error has occured with selected dates"
        end
    end

    def index
        @my_bookings = formatMyBooking(Booking.where(user_id: current_user.id))
        bookings_for_my_cars = []
        current_user.cars.each do |car|
            # Get every bookings, unless where accepted == true
            car.bookings.each { |booking| bookings_for_my_cars << booking unless booking.accepted }
        end
        @my_cars_bookings = formatMyCarsBooking(bookings_for_my_cars)
    end

    def acceptBooking
        # Set true to 'accepted' column.
        booking = Booking.find(params[:id])
        booking.accepted = true
        if booking.save
            redirect_to bookings_path, notice: "Booking successfully accepted !"
        else
            redirect_to bookings_path, alert: "An error has occured."
        end
    end

    private

    def booking_params
        params.require(:booking).permit(:starts_at, :ends_at)
    end

    def formatMyBooking(bookings)
        # Format the booking to get booking details, status 'accepted' or 'pending' and the class directly in the hash
        # To avoid logic in the view
        bookings.map { |booking| {details: booking, status: bookingStatusMessage(booking), total_price: getTotalPrice(booking)} }
    end

    def formatMyCarsBooking(bookings)
        # Format the booking to get booking details, status 'accepted' or 'pending' and the class directly in the hash
        # To avoid logic in the view
        bookings.map { |booking| {details: booking, total_price: getTotalPrice(booking)} }
    end

    def getTotalPrice(booking)
        # Return the total price of the booking
        bookings_duration_seconds = (booking.ends_at - booking.starts_at)
        bookings_duration_hours = (bookings_duration_seconds / 3600)
        bookings_duration_days = (bookings_duration_hours / 24)
        (booking.car.price_per_day * (bookings_duration_days)).round
    end

    def bookingStatusMessage(booking)
        # Format the :status value to get th emessage to display in the cards, and the class we have to apply
        booking.accepted ? {message: 'accepted', class: 'status-accepted'} : {message: 'pending...', class: 'status-pending'}
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all.reject { |car| car.user == current_user }
    end

    def show
        @car = Car.find(params[:id])
        @booking = Booking.new

        @unavailable_dates = getUnavailableDates(@car).to_json
    end

    def new
        @car = Car.new
    end

    def create
        car = Car.new(car_params)
        car.user = current_user
        if car.save
            redirect_to car_path(car), notice: 'Car successfully added !'
        else
            @car = Car.new
            redirect_to new_car_path, alert: 'An error has occured.'
        end
    end

    private

    def getUnavailableDates(car)
        # Statement of the empty array where unavailables dates for a car will be placed
        dates = []
        car.bookings.each do |booking|
            # Pushing unavailables dates during the iteration into every bookings of a car
            dates << { from: booking.starts_at, to: booking.ends_at }
        end
        dates
    end

    def car_params
        params.require(:car).permit(:brand, :model, :year_of_production, :price_per_day, :address, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    # Get the last 3 cars for the home page
    @cars = Car.where.not(user: current_user).order("created_at").limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="index-bookings-container">

    <%# MY CARS BOOKINGS SECTION %>
    <h2 class="m-bold-title">Bookings For My Own Cars</h2>
    <div class="bookings-cards-container">
        <% @my_cars_bookings.each do |booking| %>
            <div class="booking-card back-plate">
                <h3 class="s-bold-title"><%= booking[:details].car.model %></h3>
                <div class="car-card-details">
                    <p><%= booking[:details].car.brand %></p>
                    <p><%= booking[:details].car.year_of_production %></p>
                    <p><b>$<%= booking[:total_price] %></b></p>
                </div>
                <p class="fsize4"><%= "From #{booking[:details].starts_at.strftime("%A %e %B %Y %H:%M")}" %></p>
                <p class="fsize4"><%= "To #{booking[:details].ends_at.strftime("%A %e %B %Y %H:%M")}" %></p>
                <%# <%= cl_image_tag car.photo.key %>
                <% if booking[:details].car.photo.key %>      
                    <%= cl_image_tag booking[:details].car.photo.key, width: 245 %>
                <% else %>
                    <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=245&q=80" alt="">
                <% end %>
                <%= link_to 'Accept', accept_booking_path(booking[:details]), class: 'accept-cta s-bold-title', data: { turbo_method: :patch } %>
            </div>
        <% end %>
    </div>

    <%# MY BOOKINGS SECTION %>
    <h2 class="m-bold-title">My Bookings</h2>
    <div class="bookings-cards-container">
        <% @my_bookings.each do |booking| %>
            <div class="booking-card back-plate">
                <h3 class="s-bold-title"><%= booking[:details].car.model %></h3>
                <div class="car-card-details">
                    <p><%= booking[:details].car.brand %></p>
                    <p><%= booking[:details].car.year_of_production %></p>
                    <p><b>$<%= booking[:total_price] %></b></p>
                </div>
                <p class="fsize4"><%= "From #{booking[:details].starts_at.strftime("%A %e %B %Y %H:%M")}" %></p>
                <p class="fsize4"><%= "To #{booking[:details].ends_at.strftime("%A %e %B %Y %H:%M")}" %></p>
                <%# <%= cl_image_tag car.photo.key %>
                <% if booking[:details].car.photo.key %>      
                    <%= cl_image_tag booking[:details].car.photo.key, width: 245 %>
                <% else %>
                    <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=245&q=80" alt="">
                <% end %>
                <p class=<%= booking[:status][:class] %>><%= booking[:status][:message] %></p>
            </div>
        <% end %>
    </div>
</div>

app/views/cars/index.html.erb
<div class="index-cars-container">
<h2 class="m-bold-title">Our cars</h2>
    <div class="index-cars-cards-container">
        <% @cars.each do |car| %>
            <div class="car-card back-plate">
                <h3 class="s-bold-title"><%= car.model %></h3>
                <div class="car-card-details">
                    <p><%= car.brand %></p>
                    <p><%= car.year_of_production %></p>
                    <p><b>$<%= car.price_per_day %></b> /day</p>
                </div>
                <%# <%= cl_image_tag car.photo.key %>
                <% if car.photo.key %>
                    <%= cl_image_tag car.photo.key, width: 245, height: 163 %>
                <% else %>
                    <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=245&q=80" alt="">
                <% end %>
                <%= link_to 'See this car', car_path(car), class: 'secondary-cta m-title' %>
            </div>
        <% end %>
    </div>
</div>

app/views/cars/new.html.erb
<div class="new-car-container back-plate">
    <%= simple_form_for(@car) do |f| %>
        <div class="half-inputs-container">
            <%= f.input :brand,
                        autofocus: true,
                        wrapper_html: { class: "half-width-inputs" },
                        label_html: { class: "s-bold-title" }%>
            <%= f.input :model,
                        wrapper_html: { class: "half-width-inputs" },
                        label_html: { class: "s-bold-title" }%>
        </div>

        <div class="half-inputs-container">
            <%= f.input :year_of_production,
                        autofocus: true,
                        wrapper_html: { class: "half-width-inputs" },
                        input_html: { min: "1900" },
                        label_html: { class: "s-bold-title" }%>
            <%= f.input :price_per_day,
                        wrapper_html: { class: "half-width-inputs" },
                        input_html: { min: "0" },
                        label_html: { class: "s-bold-title" }%>
        </div>

        <%= f.input :photo, as: :file %>

        <%= f.input :address,
                        wrapper_html: { class: "full-width-inputs" },
                        label_html: { class: "s-bold-title" }%>

        <%= f.submit 'Rent it', class: 's-bold-title main-cta' %>
    <% end %>
</div>

app/views/cars/show.html.erb
<div class="show-car-container">
    <h2 class="m-bold-title"><%= @car.model.capitalize %></h2>
    <div class="show-car-card back-plate">
    <% if @car.photo.key %>      
        <%= cl_image_tag @car.photo.key, width: 550 %>
    <% else %>
        <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=550&q=80" alt="">
    <% end %>

        <div class="show-car-card-details">
            <div class="show-car-card-infos">
                <h3 class="s-title"><%= "#{@car.model.capitalize} - #{@car.brand.upcase}" %></h3>
                <p class="show-card-year"><%= @car.year_of_production %></p>
                <p class="show-card-address"><%= @car.address %></p>
                <p class="show-card-price-per-day"><b>$<%= @car.price_per_day %></b> /day</p>
            </div>

            <div class="show-card-book-section">
                <%= simple_form_for(@booking, url: car_bookings_path(@car)) do |f| %>
                    <p class="fsize4" id="from-label"></p>
                    <p class="fsize4" id="to-label"></p>
                    <p class="fsize4" id="recap-label"></p>

                    <%# Flatpickr's conatiner, with price_per_day and unavailables_dates values %>
                    <input type="string" placeholder="Select your dates" data-controller="flatpickr" data-flatpickr-array-value=<%= @unavailable_dates %> data-flatpickr-price-per-day-value=<%= @car.price_per_day %>>

                    <%# Simple_form inputs, where Flatipickr will put the dates %>
                    <%= f.input :starts_at, as: :hidden, input_html: { id: 'starts_at' } %>
                    <%= f.input :ends_at, as: :hidden, input_html: { id: 'ends_at' } %>
                    
                    <%= f.submit 'Book now', class: 'main-cta m-bold-title' %>
                <% end %>
            </div>

        </div>
    </div>
    <%= link_to 'Back to cars', cars_path, class: 'secondary-cta' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRentCarsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render "shared/navbar" %>

    <div class="yield-container">
      <%= yield %>
    </div>

    <%= render "shared/flashes" %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
    <div class="back-plate home-main-card">
        <h2 class="m-bold-title">How we do ?</h2>
        <div>
            <p>Take My Car is an innovative peer-to-peer car rental platform. It bridges the gap between car owners keen on monetizing their idle vehicles and drivers seeking a convenient and cost-effective rental solution. Born amid the digital revolution of the 21st century, Take My Car is a testament to the power of maximizing available resources. It is driven by a mission rooted in collaborative and responsible consumption. The booking process is straightforward and transparent, making for a pleasant and reassuring user experience. Take My Car has become a major player in the industry, reshaping the car rental landscape while providing a convenient avenue for generating extra income</p>
            <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1132&q=80" alt="An illustration of car" width="426">
        </div>
    </div>

    <div class="home-discover-or-rent-cta-conainer">
        <%= link_to 'Discover all cars', cars_path, class: "main-cta fsize3" %>
        <p class="m-bold-title">Or</p>
        <%= link_to 'Rent your own', new_car_path, class: "secondary-cta fsize3" %>
    </div>

    <hr>

    <h2 class="m-bold-title">Our latest</h2>

    <div class="home-our-latest-container">
        <% @cars.each do |car| %>
            <div class="car-card back-plate">
                <h3 class="s-bold-title"><%= car.model %></h3>
                <div class="car-card-details">
                    <p><%= car.brand %></p>
                    <p><%= car.year_of_production %></p>
                    <p><b>$<%= car.price_per_day %></b> /day</p>
                </div>
                <% if car.photo.key %>
                  <%= cl_image_tag car.photo.key, width: 245, height: 163 %>
                <% else %>
                    <img src="https://images.unsplash.com/photo-1490985830292-06e0fe60d725?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=245&q=80" alt="">
                <% end %>
                <%= link_to 'See this car', car_path(car), class: 'secondary-cta m-title' %>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="back-plate">
    <p>Made with ❤ at Le Wagon By <%= link_to 'Hugo PETAMENT', 'https://www.hugoptm.fr/', target: '_blank' %></p>
</footer>

app/views/shared/_navbar.html.erb
<header class="back-plate yield-container">
  <%= link_to 'Take My Car', root_path, class: "l-bold-title" %>

  <ul>
    <li class="s-bold-title"><%= link_to 'Cars', cars_path %></li>
    <li class="s-bold-title"><%= link_to 'Rent my Car', new_car_path %></li>
    <li class="s-bold-title"><%= link_to 'My Bookings', bookings_path %></li>
  </ul>

  <% if current_user %>
    <div class="login-register-container">
      <%= link_to 'Logout', destroy_user_session_path, class: "secondary-cta", data: { turbo_method: :delete } %>
    </div>
  <% else %>
    <div class="login-register-container">
        <%= link_to 'Login', new_user_session_path, class: "secondary-cta" %>
        <%= link_to 'Register', new_user_registration_path, class: "main-cta" %>
    </div>
  <% end %>
</header>